# Site wide configuration

title: pricelessbrewing
locale: en_US
url: http://pricelessbrewing.github.io


# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap
   - jekyll-gist

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

# Octopress

# Default extensions
post_ext: md
page_ext: md

# Found in _templates/
post_layout: post
page_layout: page

# Format titles with titlecase?
titlecase: true

# Site owner
owner:
  name: Mark
  avatar: biophoto.jpg
  bio: "Homebrewer"
  email: Pricelessbrewing@gmaii.com
  disqus-shortname: pricelessbrewing
  twitter: priceless_mark
  github: pricelessbrewing
  #facebook: #username
  #google:
  #plus: #username
  analytics: UA-60124200-1
  #verify: 
  #ad-client: 
  #ad-slot: 
  #bing-verify: 
  #stackoverflow: #http://stackoverflow.com/users/123456/username
  #linkedin: #username
  #instagram: #username
  #lastfm: #username
  #tumblr: #username
  #pinterest: #username
  #foursquare: #username
  #steam: #username
  #dribbble: #username
  #youtube: #username
  #soundcloud: #username

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
